name: cube_example
version: 1.0.0

profile: cube_example

model-paths: [models]
analysis-paths: [analyses]
test-paths: [tests]
seed-paths: [seeds]
macro-paths: [macros]
snapshot-paths: [snapshots]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  cube_example:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
  elementary:
    +schema: elementary
    enabled: "{{ target.name == 'prod' }}"

flags:
  require_explicit_package_overrides_for_builtin_materializations: false
